# Generated by Django 6.0.4 on 2026-05-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'type_product',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('natural', 'Natural'), ('juridico', 'Jurídico')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CE', 'Cédula de Extranjería'), ('CC', 'Cédula de Ciudadanía'), ('PAS', 'Pasaporte'), ('NIT', 'NIT')], max_length=5)),
                ('document_number', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='farms.farm')),
            ],
            options={
                'db_table': 'supplier',
                'constraints': [models.UniqueConstraint(fields=('farm', 'document_type', 'document_number'), name='uq_supplier_farm_document')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('minimun_stock_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farms.farm')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.unit')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.typeproduct')),
            ],
            options={
                'db_table': 'product',
                'constraints': [models.UniqueConstraint(fields=('name', 'farm'), name='uq_product_name_farm')],
            },
        ),
    ]
