# Generated by Django 6.0.4 on 2026-05-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('min_weight_g', models.FloatField()),
                ('avg_weight_g', models.FloatField()),
                ('max_weight_g', models.FloatField()),
                ('date', models.DateField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle')),
                ('source_pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_out', to='batch.pondbatch')),
                ('to_pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_in', to='batch.pondbatch')),
            ],
            options={
                'verbose_name': 'Grading Event',
                'verbose_name_plural': 'Grading Events',
                'db_table': 'grading_event',
                'ordering': ['-date'],
            },
        ),
    ]
