# Generated by Django 6.0.5 on 2026-05-18 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alert'),
        ('cycle', '0004_cycle_pond'),
        ('farms', '0003_alter_farm_water_source'),
        ('ponds', '0002_alter_pond_code'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('disease_name', models.CharField(max_length=255)),
                ('severity_level', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_stats_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_stats', to='cycle.cycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_stats', to='farms.farm')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_stats', to='ponds.pond')),
            ],
            options={
                'verbose_name': 'Health Stat',
                'verbose_name_plural': 'Health Stats',
                'db_table': 'health_stat',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dose_per_application', models.DecimalField(decimal_places=4, max_digits=10)),
                ('times_per_day', models.PositiveIntegerField()),
                ('gap_between_times_per_day', models.PositiveIntegerField(help_text='Minutos entre aplicaciones del mismo día.')),
                ('gap_between_completed_day', models.PositiveIntegerField(help_text='Días entre jornadas con aplicación (0 = todos los días).')),
                ('application_method', models.CharField(choices=[('oral', 'Oral / en alimento'), ('bath', 'Baño'), ('injection', 'Inyección'), ('water_addition', 'Adición al agua'), ('topical', 'Tópico')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='farms.farm')),
                ('health_stat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='health.healthstat')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='products.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='core.unit')),
            ],
            options={
                'db_table': 'treatment_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('application_number', models.PositiveIntegerField()),
                ('planned_dose', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_events_actual', to='core.unit')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_events_completed', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_events', to='cycle.cycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_events', to='farms.farm')),
                ('planned_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_events_planned', to='core.unit')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_events', to='health.treatmentplan')),
            ],
            options={
                'db_table': 'treatment_event',
                'ordering': ['date', 'scheduled_time', 'application_number'],
            },
        ),
        migrations.AddIndex(
            model_name='healthstat',
            index=models.Index(fields=['farm', 'cycle', 'date'], name='health_stat_farm_id_c6cfde_idx'),
        ),
        migrations.AddIndex(
            model_name='healthstat',
            index=models.Index(fields=['pond', 'date'], name='health_stat_pond_id_53d3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['health_stat', 'start_date', 'end_date'], name='treatment_p_health__1e4353_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['farm', 'status'], name='treatment_p_farm_id_f70751_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='treatment_plan_end_date_gte_start_date'),
        ),
        migrations.AddIndex(
            model_name='treatmentevent',
            index=models.Index(fields=['treatment_plan', 'date'], name='treatment_e_treatme_da104d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentevent',
            index=models.Index(fields=['cycle', 'date', 'status'], name='treatment_e_cycle_i_4d8ddc_idx'),
        ),
    ]
