# Generated by Django 6.0.5 on 2026-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='application_method',
            field=models.CharField(choices=[('oral', 'Oral (alimento medicado)'), ('water_addition', 'Adición al agua del estanque'), ('bath', 'Baño / inmersión corta')], max_length=20),
        ),
    ]
