# Generated by Django 6.0.5 on 2026-05-30 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alert'),
        ('farms', '0003_alter_farm_water_source'),
        ('harvest', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('natural', 'Natural'), ('juridico', 'Jurídico')], max_length=20, verbose_name='Tipo de cliente')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('document_type', models.CharField(choices=[('CE', 'Cédula de Extranjería'), ('CC', 'Cédula de Ciudadanía'), ('PAS', 'Pasaporte'), ('NIT', 'NIT'), ('PPT', 'Permiso por Protección Temporal')], max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='farms.farm', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Número de factura')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='farms.farm', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='farms.farm', verbose_name='Finca')),
                ('harvest_classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='harvest.harvestclassification', verbose_name='Clasificación de cosecha')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale', verbose_name='Venta')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='core.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('farm', 'document_type', 'document_number'), name='unique_client_document_per_farm'),
        ),
    ]
