# Generated by Django 6.0.5 on 2026-05-31 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='fish_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de peces'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='quantity_g',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad (g)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio total del detalle'),
        ),
    ]
