# Generated by Django 6.0.4 on 2026-04-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_temp_password'),
        ('farms', '__first__'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='invitation_farm_id_ececd5_idx',
            old_name='invitation_farm_id_51f0ae_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='farm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
