<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-30 22:04

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.7 on 2026-04-16 00:15

import django.core.validators
import django.utils.timezone
>>>>>>> origin/backend
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/backend
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('cleaning', 'En limpieza'), ('in_use', 'En uso')], default='active', max_length=20)),
                ('type', models.CharField(choices=[('dirt', 'Tierra'), ('concrete', 'Concreto'), ('geomembrane', 'Geomembrana'), ('floating_cage', 'Jaula flotante'), ('raceway', 'Canal'), ('round_tank', 'Tanque redondo')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='farms.farm')),
            ],
            options={
                'db_table': 'pond',
            },
        ),
        migrations.CreateModel(
            name='UserFarmPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_ponds', to='farms.farm')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_ponds', to='ponds.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_ponds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_farm_pond',
            },
        ),
        migrations.AddConstraint(
            model_name='pond',
            constraint=models.UniqueConstraint(fields=('name', 'farm'), name='uq_pond_name_farm'),
        ),
        migrations.AddConstraint(
            model_name='pond',
            constraint=models.UniqueConstraint(fields=('code', 'farm'), name='uq_pond_code_farm'),
        ),
        migrations.AddConstraint(
            model_name='userfarmpond',
            constraint=models.UniqueConstraint(fields=('user', 'farm', 'pond'), name='uq_user_farm_pond'),
        ),
=======
            name='Estanque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('granja_id', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('estanque', 'Estanque'), ('jaula', 'Jaula')], default='estanque', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_uso', 'En Uso'), ('en_limpieza', 'En Limpieza'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo_interruptor', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'estanque',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('granja_id', 'codigo'), name='unique_codigo_por_granja')],
            },
        ),
>>>>>>> origin/backend
    ]
