# Generated by Django 6.0.4 on 2026-04-30 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('cleaning', 'En limpieza'), ('in_use', 'En uso')], default='active', max_length=20)),
                ('type', models.CharField(choices=[('dirt', 'Tierra'), ('concrete', 'Concreto'), ('geomembrane', 'Geomembrana'), ('floating_cage', 'Jaula flotante'), ('raceway', 'Canal'), ('round_tank', 'Tanque redondo')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='farms.farm')),
            ],
            options={
                'db_table': 'pond',
            },
        ),
        migrations.CreateModel(
            name='UserFarmPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_ponds', to='farms.farm')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_ponds', to='ponds.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_ponds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_farm_pond',
            },
        ),
        migrations.AddConstraint(
            model_name='pond',
            constraint=models.UniqueConstraint(fields=('name', 'farm'), name='uq_pond_name_farm'),
        ),
        migrations.AddConstraint(
            model_name='pond',
            constraint=models.UniqueConstraint(fields=('code', 'farm'), name='uq_pond_code_farm'),
        ),
        migrations.AddConstraint(
            model_name='userfarmpond',
            constraint=models.UniqueConstraint(fields=('user', 'farm', 'pond'), name='uq_user_farm_pond'),
        ),
    ]
