# Generated by Django 5.2.7 on 2026-04-16 00:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('granja_id', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('estanque', 'Estanque'), ('jaula', 'Jaula')], default='estanque', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_uso', 'En Uso'), ('en_limpieza', 'En Limpieza'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo_interruptor', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'estanque',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('granja_id', 'codigo'), name='unique_codigo_por_granja')],
            },
        ),
    ]
