# Generated by Django 6.0.4 on 2026-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='code',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
