# Generated by Django 5.2.7 on 2026-04-19 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0002_rename_to_pond_and_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pond',
            name='type',
        ),
        migrations.AddField(
            model_name='pond',
            name='area',
            field=models.FloatField(default=0.01, help_text='Area in m²', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='pond',
            name='depth',
            field=models.FloatField(default=0.01, help_text='Depth in m', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='pond',
            name='volume',
            field=models.FloatField(default=0.01, help_text='Volume in m³', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='pond',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
