# Generated by Django 6.0.4 on 2026-04-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='deleted_at',
        ),
    ]
