# Generated by Django 6.0.4 on 2026-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
