# Generated by Django 6.0.4 on 2026-04-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password_reset_expiry_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.TextField(null=True),
        ),
    ]
