# Generated by Django 6.0.4 on 2026-04-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type_source', models.CharField(choices=[('User', 'User'), ('UserFarm', 'UserFarm'), ('Farm', 'Farm'), ('FarmRole', 'FarmRole'), ('Pond', 'Pond'), ('UserFarmPond', 'UserFarmPond'), ('TypeProduct', 'TypeProduct'), ('Product', 'Product'), ('PurchaseDetail', 'PurchaseDetail'), ('Supplier', 'Supplier'), ('Specie', 'Specie'), ('SpecieParameter', 'SpecieParameter'), ('SpecieFeedingReference', 'SpecieFeedingReference'), ('SpecieProductionReference', 'SpecieProductionReference'), ('Batch', 'Batch'), ('ProductionPlan', 'ProductionPlan'), ('Cycle', 'Cycle'), ('FeedingSchedule', 'FeedingSchedule'), ('FeedingPlan', 'FeedingPlan'), ('FeedingEvent', 'FeedingEvent'), ('DailyStat', 'DailyStat'), ('ProductUsageLog', 'ProductUsageLog'), ('ControlStat', 'ControlStat'), ('FishEvaluated', 'FishEvaluated'), ('HealthStat', 'HealthStat'), ('TreatmentPlan', 'TreatmentPlan'), ('TreatmentEvent', 'TreatmentEvent'), ('AmbientalMeasurement', 'AmbientalMeasurement'), ('Alert', 'Alert'), ('Sale', 'Sale'), ('InventoryMovement', 'InventoryMovement'), ('Harvest', 'Harvest'), ('HarvestClassification', 'HarvestClassification'), ('Client', 'Client'), ('Buy', 'Buy'), ('Invitation', 'Invitation'), ('BatchTransfer', 'BatchTransfer'), ('GradingEvent', 'GradingEvent'), ('SaleDetail', 'SaleDetail'), ('CycleBatch', 'CycleBatch'), ('PondBatch', 'PondBatch'), ('SpeciePondType', 'SpeciePondType')], max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'), models.Index(fields=['farm_id'], name='audit_log_farm_id_14aee8_idx'), models.Index(fields=['type_source'], name='audit_log_type_so_8ea6be_idx'), models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx')],
            },
        ),
    ]
