# Generated by Django 6.0.4 on 2026-05-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='type_source',
            field=models.CharField(choices=[('User', 'User'), ('UserFarm', 'UserFarm'), ('Farm', 'Farm'), ('FarmRole', 'FarmRole'), ('Pond', 'Pond'), ('UserFarmPond', 'UserFarmPond'), ('TypeProduct', 'TypeProduct'), ('Product', 'Product'), ('PurchaseDetail', 'PurchaseDetail'), ('Supplier', 'Supplier'), ('Specie', 'Specie'), ('SpecieParameter', 'SpecieParameter'), ('SpecieFeedingReference', 'SpecieFeedingReference'), ('SpecieProductionReference', 'SpecieProductionReference'), ('Batch', 'Batch'), ('ProductionPlan', 'ProductionPlan'), ('Cycle', 'Cycle'), ('FeedingSchedule', 'FeedingSchedule'), ('FeedingPlan', 'FeedingPlan'), ('FeedingEvent', 'FeedingEvent'), ('DailyStat', 'DailyStat'), ('ProductUsageLog', 'ProductUsageLog'), ('ControlStat', 'ControlStat'), ('FishEvaluated', 'FishEvaluated'), ('HealthStat', 'HealthStat'), ('TreatmentPlan', 'TreatmentPlan'), ('TreatmentEvent', 'TreatmentEvent'), ('AmbientalMeasurement', 'AmbientalMeasurement'), ('Alert', 'Alert'), ('Sale', 'Sale'), ('InventoryMovement', 'InventoryMovement'), ('Harvest', 'Harvest'), ('HarvestClassification', 'HarvestClassification'), ('Client', 'Client'), ('Buy', 'Buy'), ('Invitation', 'Invitation'), ('BatchTransfer', 'BatchTransfer'), ('GradingEvent', 'GradingEvent'), ('SaleDetail', 'SaleDetail'), ('CyclePondBatch', 'Cycle Pond Batch'), ('PondBatch', 'PondBatch'), ('SpeciePondType', 'SpeciePondType')], max_length=50),
        ),
    ]
