# Generated by Django 6.0.5 on 2026-05-11 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_type_source'),
        ('cycle', '0003_rename_cyclebatch_cyclepondbatch_and_more'),
        ('farms', '0003_alter_farm_water_source'),
        ('ponds', '0002_alter_pond_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('Health', 'Salud'), ('Stock', 'Stock'), ('Ambiental', 'Ambiental'), ('Control', 'Control'), ('Feeding', 'Alimentación')], max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cycle.cycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.farm')),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ponds.pond')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'is_resolved'], name='alert_farm_id_d4934a_idx'), models.Index(fields=['source_type', 'source_id'], name='alert_source__7839be_idx'), models.Index(fields=['severity'], name='alert_severit_877930_idx')],
            },
        ),
    ]
