# Generated by Django 6.0.4 on 2026-05-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
        ('ponds', '0002_alter_pond_code'),
        ('species', '0002_speciefeedingreference_uq_specie_feeding_reference_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('estimated_finish_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('min_weight_g', models.FloatField(blank=True, null=True)),
                ('avg_weight_g', models.FloatField(blank=True, null=True)),
                ('max_weight_g', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'db_table': 'cycle',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('min_weight_g', models.FloatField()),
                ('avg_weight_g', models.FloatField()),
                ('max_weight_g', models.FloatField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle')),
                ('pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.pondbatch')),
            ],
            options={
                'verbose_name': 'Cycle Batch',
                'verbose_name_plural': 'Cycle Batches',
                'db_table': 'cycle_batch',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('nursery', 'Nursery'), ('growout', 'Growout'), ('breeding', 'Breeding')], max_length=20)),
                ('total_days', models.PositiveIntegerField()),
                ('expected_mortality_rate', models.FloatField()),
                ('expected_final_weight', models.FloatField()),
                ('expected_reproduction_rate', models.FloatField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle.productionplan')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
                'db_table': 'production_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='production_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cycle.productionplan'),
        ),
    ]
