# Generated by Django 6.0.4 on 2026-05-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='pond',
        ),
    ]
