# Generated by Django 6.0.4 on 2026-05-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('cycle', '0002_remove_cycle_pond'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CycleBatch',
            new_name='CyclePondBatch',
        ),
        migrations.AlterModelOptions(
            name='cyclepondbatch',
            options={'ordering': ['-id'], 'verbose_name': 'Cycle Pond Batch', 'verbose_name_plural': 'Cycle Pond Batches'},
        ),
    ]
