# Generated by Django 6.0.4 on 2026-05-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_rename_cyclebatch_cyclepondbatch_and_more'),
        ('ponds', '0002_alter_pond_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='pond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ponds.pond'),
        ),
    ]
