# Generated by Django 6.0.4 on 2026-05-18 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('cycle', '0004_cycle_pond'),
        ('farms', '0003_alter_farm_water_source'),
        ('ponds', '0002_alter_pond_code'),
        ('species', '0003_remove_speciefeedingreference_uq_specie_feeding_reference_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyclepondbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cycle Pond Batch', 'verbose_name_plural': 'Cycle Pond Batches'},
        ),
        migrations.AddField(
            model_name='cyclepondbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyclepondbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ponds.pond'),
        ),
        migrations.AlterField(
            model_name='cyclepondbatch',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_pond_batches', to='cycle.cycle'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['farm', 'pond', 'deleted_at'], name='cycle_farm_id_734e09_idx'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['pond', 'state', 'deleted_at'], name='cycle_pond_id_8c98fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclepondbatch',
            index=models.Index(fields=['cycle', 'pond_batch'], name='cycle_batch_cycle_i_0e9b22_idx'),
        ),
    ]
