# Generated by Django 6.0.5 on 2026-05-31 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('cycle', '0005_make_pond_required_add_indexes_timestamps'),
        ('farms', '0003_alter_farm_water_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_fish_count', models.PositiveIntegerField()),
                ('total_weight_g', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_weight_g', models.FloatField(default=0)),
                ('avg_weight_g', models.FloatField(default=0)),
                ('max_weight_g', models.FloatField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('Total', 'Total'), ('Partial', 'Parcial')], max_length=10)),
                ('traceability_mode', models.CharField(choices=[('proportional', 'Proportional'), ('exact', 'Exact')], default='proportional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='cycle.cycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farms.farm')),
            ],
            options={
                'db_table': 'harvest',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_category', models.CharField(choices=[('Small', 'Pequeño'), ('Medium', 'Mediano'), ('Large', 'Grande'), ('Extra Large', 'Extra Grande')], max_length=15)),
                ('fish_count', models.PositiveIntegerField()),
                ('total_weight_g', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_classifications', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_classifications', to='farms.farm')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='harvest.harvest')),
            ],
            options={
                'db_table': 'harvest_classification',
            },
        ),
        migrations.CreateModel(
            name='HarvestClassificationDerivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_count', models.PositiveIntegerField()),
                ('total_weight_g', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pond_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_derivation', to='batch.batch')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivations', to='harvest.harvestclassification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_derivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'harvest_classification_derivation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestClassificationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_count', models.PositiveIntegerField()),
                ('total_weight_g', models.DecimalField(decimal_places=2, max_digits=14)),
                ('traceability_type', models.CharField(choices=[('exact', 'Exact'), ('proportional', 'Proportional')], default='proportional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='harvest.harvestclassification')),
                ('cycle_pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_classification_sources', to='cycle.cyclepondbatch')),
            ],
            options={
                'db_table': 'harvest_classification_source',
            },
        ),
        migrations.CreateModel(
            name='HarvestSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_count', models.PositiveIntegerField()),
                ('total_weight_g', models.DecimalField(decimal_places=2, max_digits=14)),
                ('traceability_type', models.CharField(choices=[('exact', 'Exact'), ('estimated', 'Estimated'), ('proportional', 'Proportional')], default='proportional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle_pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_sources', to='cycle.cyclepondbatch')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='harvest.harvest')),
            ],
            options={
                'db_table': 'harvest_source',
            },
        ),
        migrations.AddConstraint(
            model_name='harvestclassification',
            constraint=models.UniqueConstraint(fields=('harvest', 'size_category'), name='uq_harvest_size_category'),
        ),
        migrations.AddConstraint(
            model_name='harvestclassificationsource',
            constraint=models.UniqueConstraint(fields=('classification', 'cycle_pond_batch'), name='uq_harvest_classification_source_batch'),
        ),
        migrations.AddConstraint(
            model_name='harvestsource',
            constraint=models.UniqueConstraint(fields=('harvest', 'cycle_pond_batch'), name='uq_harvest_source_cycle_pond_batch'),
        ),
    ]
