services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: configs.dev_settings
      DATABASE_NAME: pg
      DATABASE_USER: waos
      DATABASE_PASSWORD: wiiw
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_HOST_USER: pawsy1225@gmail.com
      EMAIL_HOST_PASSWORD: snih gqwz fcyc qzkv
      DEFAULT_FROM_EMAIL: pawsy1225@gmail.com
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: waos
      POSTGRES_PASSWORD: wiiw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
