MODULE_FEEDING = "feeding"
MODULE_BIOMETRY = "biometry"
MODULE_HEALTH = "health"
MODULE_HARVEST = "harvest"
MODULE_SALES = "sales"

ALL_MODULES = (
    MODULE_FEEDING,
    MODULE_BIOMETRY,
    MODULE_HEALTH,
    MODULE_HARVEST,
    MODULE_SALES,
)

MODULE_LABELS = {
    MODULE_FEEDING: "Alimentación",
    MODULE_BIOMETRY: "Biometría",
    MODULE_HEALTH: "Sanidad",
    MODULE_HARVEST: "Cosecha",
    MODULE_SALES: "Ventas",
}

MODULE_COLORS = {
    MODULE_FEEDING: "#0D4F5C",  
    MODULE_BIOMETRY: "#0D4F5C",
    MODULE_HEALTH: "#0D4F5C",  
    MODULE_HARVEST: "#0D4F5C",  
    MODULE_SALES: "#0D4F5C",   
}

FORMAT_PDF = "pdf"
FORMAT_XLSX = "xlsx"

EXPORT_FORMATS = (FORMAT_PDF, FORMAT_XLSX)
