# Generated by Django 6.0.4 on 2026-05-09 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
        ('cycle', '0001_initial'),
        ('farms', '0003_alter_farm_water_source'),
        ('products', '0001_initial'),
        ('species', '0003_remove_speciefeedingreference_uq_specie_feeding_reference_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_plans', to='cycle.cycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='farms.farm')),
            ],
            options={
                'db_table': 'feeding_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('ration_number', models.PositiveIntegerField()),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeding_events_actual', to='core.unit')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_events_completed', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_events', to='cycle.cycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_events', to='farms.farm')),
                ('planned_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_events_planned', to='core.unit')),
                ('feeding_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_events', to='feeding.feedingplan')),
            ],
            options={
                'db_table': 'feeding_event',
                'ordering': ['date', 'scheduled_time', 'ration_number'],
            },
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('alevin', 'Alevín'), ('rising', 'Levante'), ('fatting', 'Engorde'), ('breeding', 'Reproducción')], max_length=20)),
                ('aceptable_min_weight_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aceptable_max_weight_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feed_form', models.CharField(choices=[('pellet', 'Pellet'), ('extruded', 'Extruido'), ('crumble', 'Migaja'), ('powder', 'Polvo')], max_length=20)),
                ('pellet_size_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feeding_rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('times_per_day', models.PositiveIntegerField()),
                ('gap_between_times_per_day', models.PositiveIntegerField(help_text='Minutos entre raciones del mismo día')),
                ('gap_between_completed_day', models.PositiveIntegerField(help_text='Días entre jornadas de alimentación (0 = todos los días; 1 = día sí día no; etc.).')),
                ('expected_fca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_daily_gain_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_schedules', to='farms.farm')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='feeding.feedingschedule')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_schedules', to='products.product')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_schedules', to='species.specie')),
            ],
            options={
                'db_table': 'feeding_schedule',
            },
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='feeding_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_plans', to='feeding.feedingschedule'),
        ),
    ]
