# Generated by Django 6.0.4 on 2026-05-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
        ('ponds', '0002_alter_pond_code'),
        ('species', '0002_speciefeedingreference_uq_specie_feeding_reference_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_type', models.CharField(choices=[('harvest_classification', 'Harvest Classification'), ('purchase_detail', 'Purchase Detail'), ('initial', 'Initial')], default='initial', max_length=50)),
                ('origin_id', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('biological_state', models.CharField(choices=[('alevin', 'Alevin'), ('rising', 'Rising'), ('fatting', 'Fatting'), ('breeding', 'Breeding')], default='alevin', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('finished', 'Finished'), ('dead', 'Dead')], default='active', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('min_weight_g', models.FloatField()),
                ('avg_weight_g', models.FloatField()),
                ('max_weight_g', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
                'ordering': ['-created_at'],
                'unique_together': {('code', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='PondBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond')),
            ],
            options={
                'verbose_name': 'Pond Batch',
                'verbose_name_plural': 'Pond Batches',
                'db_table': 'pond_batch',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('source_pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='batch.pondbatch')),
                ('to_pond_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='batch.pondbatch')),
            ],
            options={
                'verbose_name': 'Batch Transfer',
                'verbose_name_plural': 'Batch Transfers',
                'db_table': 'batch_transfer',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BatchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('child_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='batch.batch')),
                ('parent_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='batch.batch')),
            ],
            options={
                'verbose_name': 'Batch Source',
                'verbose_name_plural': 'Batch Sources',
                'db_table': 'batch_source',
                'unique_together': {('parent_batch', 'child_batch')},
            },
        ),
    ]
