# Generated by Django 6.0.4 on 2026-05-17 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('cycle', '0004_cycle_pond'),
        ('ponds', '0002_alter_pond_code'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='cycle.cycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='ponds.pond')),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'db_table': 'daily_stat',
                'ordering': ['-stat_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('l', 'Litros'), ('unit', 'Unidades')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batch.batch')),
                ('daily_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='monitoring.dailystat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Usage Log',
                'verbose_name_plural': 'Product Usage Logs',
                'db_table': 'product_usage_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateField()),
                ('sampled_quantity', models.PositiveIntegerField()),
                ('live_quantity', models.PositiveIntegerField()),
                ('min_weight_g', models.FloatField()),
                ('avg_weight_g', models.FloatField()),
                ('max_weight_g', models.FloatField()),
                ('mortality_percentage', models.FloatField()),
                ('biomass_kg', models.FloatField()),
                ('fca', models.FloatField(blank=True, null=True)),
                ('biomass_gain_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_stats', to='cycle.cycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_stats', to='ponds.pond')),
            ],
            options={
                'verbose_name': 'Control Stat',
                'verbose_name_plural': 'Control Stats',
                'db_table': 'control_stat',
                'ordering': ['-control_date'],
                'unique_together': {('cycle', 'pond', 'control_date')},
            },
        ),
        migrations.CreateModel(
            name='FishEvaluated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('sampled_quantity', models.PositiveIntegerField()),
                ('min_weight_g', models.FloatField()),
                ('avg_weight_g', models.FloatField()),
                ('max_weight_g', models.FloatField()),
                ('mortality_quantity', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_evaluations', to='cycle.cycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_evaluations', to='ponds.pond')),
            ],
            options={
                'verbose_name': 'Fish Evaluation',
                'verbose_name_plural': 'Fish Evaluations',
                'db_table': 'fish_evaluated',
                'ordering': ['-evaluation_date'],
                'unique_together': {('cycle', 'evaluation_date', 'pond')},
            },
        ),
    ]
