# Generated by Django 6.0.4 on 2026-05-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert'),
        ('farms', '0003_alter_farm_water_source'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_stats_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlstat',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_stats', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='fishevaluated',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fish_evaluations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fishevaluated',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_evaluations', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='productusagelog',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_usage_logs', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='productusagelog',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_usages', to='core.unit'),
        ),
    ]
