# Generated by Django 6.0.4 on 2026-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_add_farm_created_by_unit_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishevaluated',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID de ControlStat si type=control_stat, ID de evento de salud si type=health_stat', null=True),
        ),
        migrations.AddField(
            model_name='fishevaluated',
            name='type',
            field=models.CharField(choices=[('control_stat', 'Control Stat'), ('health_stat', 'Health Stat')], default='health_stat', max_length=20),
        ),
    ]
