# Generated by Django 6.0.4 on 2026-05-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_add_type_source_id_to_fish_evaluated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fishevaluated',
            unique_together=set(),
        ),
    ]
