# Generated by Django 6.0.4 on 2026-04-15 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
        ('user', '0005_alter_user_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='farm',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='user.manager'),
        ),
    ]
