# Generated by Django 6.0.4 on 2026-04-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_farm_deleted_at_farm_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='village',
        ),
        migrations.AddField(
            model_name='farm',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, choices=[('Leticia', 'Leticia'), ('Puerto Nariño', 'Puerto Nariño'), ('Medellín', 'Medellín'), ('Bello', 'Bello'), ('Itagüí', 'Itagüí'), ('Envigado', 'Envigado'), ('Rionegro', 'Rionegro'), ('Apartadó', 'Apartadó'), ('Turbo', 'Turbo'), ('Caucasia', 'Caucasia'), ('Arauca', 'Arauca'), ('Saravena', 'Saravena'), ('Tame', 'Tame'), ('Barranquilla', 'Barranquilla'), ('Soledad', 'Soledad'), ('Malambo', 'Malambo'), ('Sabanalarga', 'Sabanalarga'), ('Cartagena', 'Cartagena'), ('Magangué', 'Magangué'), ('Mompox', 'Mompox'), ('Tunja', 'Tunja'), ('Sogamoso', 'Sogamoso'), ('Duitama', 'Duitama'), ('Chiquinquirá', 'Chiquinquirá'), ('Paipa', 'Paipa'), ('Manizales', 'Manizales'), ('La Dorada', 'La Dorada'), ('Riosucio', 'Riosucio'), ('Chinchiná', 'Chinchiná'), ('Florencia', 'Florencia'), ('San Vicente del Caguán', 'San Vicente del Caguán'), ('Yopal', 'Yopal'), ('Aguazul', 'Aguazul'), ('Villanueva', 'Villanueva'), ('Popayán', 'Popayán'), ('Santander de Quilichao', 'Santander de Quilichao'), ('Puerto Tejada', 'Puerto Tejada'), ('Valledupar', 'Valledupar'), ('Aguachica', 'Aguachica'), ('Bosconia', 'Bosconia'), ('Quibdó', 'Quibdó'), ('Istmina', 'Istmina'), ('Montería', 'Montería'), ('Lorica', 'Lorica'), ('Cereté', 'Cereté'), ('Sahagún', 'Sahagún'), ('Bogotá', 'Bogotá'), ('Soacha', 'Soacha'), ('Zipaquirá', 'Zipaquirá'), ('Fusagasugá', 'Fusagasugá'), ('Girardot', 'Girardot'), ('Facatativá', 'Facatativá'), ('Chía', 'Chía'), ('Mosquera', 'Mosquera'), ('Inírida', 'Inírida'), ('San José del Guaviare', 'San José del Guaviare'), ('Neiva', 'Neiva'), ('Pitalito', 'Pitalito'), ('Garzón', 'Garzón'), ('Riohacha', 'Riohacha'), ('Maicao', 'Maicao'), ('Uribia', 'Uribia'), ('Santa Marta', 'Santa Marta'), ('Ciénaga', 'Ciénaga'), ('El Banco', 'El Banco'), ('Fundación', 'Fundación'), ('Villavicencio', 'Villavicencio'), ('Acacías', 'Acacías'), ('Granada', 'Granada'), ('Pasto', 'Pasto'), ('Tumaco', 'Tumaco'), ('Ipiales', 'Ipiales'), ('Túquerres', 'Túquerres'), ('Cúcuta', 'Cúcuta'), ('Ocaña', 'Ocaña'), ('Pamplona', 'Pamplona'), ('Villa del Rosario', 'Villa del Rosario'), ('Mocoa', 'Mocoa'), ('Puerto Asís', 'Puerto Asís'), ('Orito', 'Orito'), ('Armenia', 'Armenia'), ('Calarcá', 'Calarcá'), ('Montenegro', 'Montenegro'), ('Pereira', 'Pereira'), ('Dosquebradas', 'Dosquebradas'), ('Santa Rosa de Cabal', 'Santa Rosa de Cabal'), ('San Andrés', 'San Andrés'), ('Providencia', 'Providencia'), ('Bucaramanga', 'Bucaramanga'), ('Floridablanca', 'Floridablanca'), ('Girón', 'Girón'), ('Barrancabermeja', 'Barrancabermeja'), ('San Gil', 'San Gil'), ('Socorro', 'Socorro'), ('Sincelejo', 'Sincelejo'), ('Corozal', 'Corozal'), ('San Marcos', 'San Marcos'), ('Ibagué', 'Ibagué'), ('Espinal', 'Espinal'), ('Honda', 'Honda'), ('Melgar', 'Melgar'), ('Cali', 'Cali'), ('Buenaventura', 'Buenaventura'), ('Palmira', 'Palmira'), ('Tuluá', 'Tuluá'), ('Buga', 'Buga'), ('Cartago', 'Cartago'), ('Jamundí', 'Jamundí'), ('Mitú', 'Mitú'), ('Puerto Carreño', 'Puerto Carreño')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='department',
            field=models.CharField(blank=True, choices=[('amazonas', 'Amazonas'), ('antioquia', 'Antioquia'), ('arauca', 'Arauca'), ('atlantico', 'Atlántico'), ('bolivar', 'Bolívar'), ('boyaca', 'Boyacá'), ('caldas', 'Caldas'), ('caqueta', 'Caquetá'), ('casanare', 'Casanare'), ('cauca', 'Cauca'), ('cesar', 'Cesar'), ('choco', 'Chocó'), ('cordoba', 'Córdoba'), ('cundinamarca', 'Cundinamarca'), ('guainia', 'Guainía'), ('guaviare', 'Guaviare'), ('huila', 'Huila'), ('la_guajira', 'La Guajira'), ('magdalena', 'Magdalena'), ('meta', 'Meta'), ('narino', 'Nariño'), ('norte_de_santander', 'Norte de Santander'), ('putumayo', 'Putumayo'), ('quindio', 'Quindío'), ('risaralda', 'Risaralda'), ('san_andres', 'San Andrés y Providencia'), ('santander', 'Santander'), ('sucre', 'Sucre'), ('tolima', 'Tolima'), ('valle_del_cauca', 'Valle del Cauca'), ('vaupes', 'Vaupés'), ('vichada', 'Vichada')], max_length=100, null=True),
        ),
    ]
