# Generated by Django 6.0.4 on 2026-04-29 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('total_area_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_source', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farm',
            },
        ),
        migrations.CreateModel(
            name='FarmRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.PositiveSmallIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='farms.farm')),
            ],
            options={
                'db_table': 'farm_role',
            },
        ),
        migrations.CreateModel(
            name='UserFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Trabaja actualmente'), ('inactive', 'No trabaja actualmente')], default='active', max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farms', to='farms.farm')),
                ('farm_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_farms', to='farms.farmrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_farm',
                'constraints': [models.UniqueConstraint(fields=('user', 'farm'), name='uq_user_farm')],
            },
        ),
    ]
