# Generated by Django 6.0.4 on 2026-05-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='water_source',
            field=models.CharField(blank=True, choices=[('river', 'Río'), ('stream', 'Quebrada'), ('lake', 'Lago/Laguna'), ('spring', 'Manantial'), ('reservoir', 'Embalse'), ('deep_well', 'Pozo profundo'), ('municipal', 'Acueducto municipal'), ('irrigation_canal', 'Canal de riego'), ('rainwater', 'Agua lluvia')], max_length=20),
        ),
    ]
