# Generated by Django 6.0.4 on 2026-05-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('feeding_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Specie',
                'verbose_name_plural': 'Species',
                'db_table': 'specie',
            },
        ),
        migrations.CreateModel(
            name='SpecieFeedingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('alevin', 'Alevín'), ('rising', 'Levante'), ('fatting', 'Engorde'), ('breeding', 'Reproducción')], max_length=20)),
                ('min_weight_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_protein_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommended_pellet_size_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommended_feed_form', models.CharField(choices=[('pellet', 'Pellet'), ('extruded', 'Extruido'), ('crumble', 'Migaja'), ('powder', 'Polvo')], max_length=20)),
                ('recommended_feeding_rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reference_fca_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reference_fca_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reference_daily_gain_g_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reference_daily_gain_g_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_references', to='species.specie')),
            ],
            options={
                'db_table': 'specie_feeding_reference',
            },
        ),
        migrations.CreateModel(
            name='SpecieParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('temperature', 'Temperatura'), ('dissolved_oxygen', 'Oxígeno disuelto'), ('ph', 'pH'), ('turbidity', 'Turbidez'), ('alkalinity', 'Alcalinidad'), ('conductivity', 'Conductividad')], max_length=20)),
                ('min_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('alert_threshold', models.DecimalField(decimal_places=4, max_digits=10)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='species.specie')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specie_parameters', to='core.unit')),
            ],
            options={
                'db_table': 'specie_parameter',
            },
        ),
        migrations.CreateModel(
            name='SpecieProductionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nursery', 'Alevinaje'), ('growout', 'Engorde'), ('breeding', 'Reproducción')], max_length=20)),
                ('reference_total_days_min', models.PositiveIntegerField()),
                ('reference_total_days_max', models.PositiveIntegerField()),
                ('reference_mortality_rate_min', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reference_mortality_rate_max', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reference_final_weight_min_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_final_weight_max_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_reproduction_rate_min', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reference_reproduction_rate_max', models.DecimalField(decimal_places=4, max_digits=5)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_references', to='species.specie')),
            ],
            options={
                'db_table': 'specie_production_reference',
            },
        ),
        migrations.CreateModel(
            name='SpeciePondType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_type', models.CharField(choices=[('dirt', 'Tierra'), ('concrete', 'Concreto'), ('geomembrane', 'Geomembrana'), ('floating_cage', 'Jaula flotante'), ('raceway', 'Canal'), ('round_tank', 'Tanque redondo')], max_length=20)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_types', to='species.specie')),
            ],
            options={
                'db_table': 'specie_pond_type',
                'constraints': [models.UniqueConstraint(fields=('specie', 'pond_type'), name='uq_specie_pond_type')],
            },
        ),
    ]
