# Generated by Django 6.0.4 on 2026-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='speciefeedingreference',
            constraint=models.UniqueConstraint(fields=('specie', 'stage'), name='uq_specie_feeding_reference_stage'),
        ),
        migrations.AddConstraint(
            model_name='specieparameter',
            constraint=models.UniqueConstraint(fields=('specie', 'parameter_type'), name='uq_specie_parameter_type'),
        ),
        migrations.AddConstraint(
            model_name='specieproductionreference',
            constraint=models.UniqueConstraint(fields=('specie', 'type'), name='uq_specie_production_reference_type'),
        ),
    ]
