# Generated by Django 6.0.4 on 2026-05-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_speciefeedingreference_uq_specie_feeding_reference_stage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speciefeedingreference',
            name='uq_specie_feeding_reference_stage',
        ),
        migrations.AddConstraint(
            model_name='speciefeedingreference',
            constraint=models.UniqueConstraint(fields=('specie', 'stage', 'recommended_feed_form'), name='uq_specie_feeding_reference_stage_feed_form'),
        ),
    ]
