# Generated by Django 6.0.4 on 2026-05-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
        ('farms', '0002_city_department_alter_farm_city_city_department_and_more'),
        ('ponds', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='farms.farm')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buys', to='products.supplier')),
            ],
            options={
                'db_table': 'buy',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchases.buy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='products.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='core.unit')),
            ],
            options={
                'db_table': 'purchase_detail',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.PositiveIntegerField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('In', 'Entrada'), ('Out', 'Salida'), ('Initial', 'Inicial')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observations', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, choices=[('Purchase', 'Compra'), ('Feeding', 'Alimentación'), ('Health', 'Salud'), ('Daily', 'Diario')], max_length=20, null=True)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='farms.farm')),
                ('pond_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ponds.pond')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product')),
            ],
            options={
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'product'], name='inventory_m_farm_id_db4c0f_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_m_source__90fe57_idx')],
            },
        ),
    ]
