# Generated by Django 6.0.5 on 2026-05-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_rename_cyclebatch_cyclepondbatch_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='cycle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle'),
        ),
    ]
